In [6]:
 # Introduction to Tensors

In [7]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [8]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
# Check the number of dimensions of a tensor (ndim stands for nummber of dimensions)
scalar.ndim

0

In [10]:
# Create a vector 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
  vector.ndim

1

In [12]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])

In [13]:
matrix.ndim

2

In [14]:
# Create another matrix 
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
# What do you thnk the number of dimensions of the matrics are
another_matrix.ndim

2

In [16]:
# Lets create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
tensor.ndim

3

###Creating tensors with tf.Variable


In [18]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [20]:
# Lets try change one of the elements in our changiable_tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [21]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored


Creating random tensors


In [ ]:

 # Create  two random(but the same) tensors
 random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
 random_1 = random_1.normal(shape=(3, 2))
 random_2 = tf.random.Generator.from_seed(42)
 random_2 = random_2.normal(shape=(3, 2)

 # Are they equal?
 random_1, random_2, random_1 == random_2

In [ ]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

Shuffle the order of elements in a tensor



In [ ]:
# Shuffle a tensor
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
not_shuffled.ndim
# Shuffle our non_shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

It looks like if we want our shuffled tensors to be the same order, we've got to use the global level random seed as well as the operation level random seed:
Rule4: "If both the global and operation seed are set: Both seeds are used in conjuction to determine the random sequence."

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

In [ ]:
# Other ways to make tensors
tf.ones([10, 7])

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape=(3, 4))

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU computing faster

In [ ]:
# You can also change numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A


In [ ]:
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A


In [ ]:
rank_4_tensor = tf.zeros(shape=)

In [ ]:
### Getting information from tensors
# Create  a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
2*3*4*5

In [ ]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in oour tensor:", tf.size(rank_4_tensor).numpy())

Tensors can be done just as python list


In [ ]:
# Create a new tensor with 
tf.__version__

In [ ]:
B = tf.constant([1.7, 7.4])
B.dtype

In [ ]:
C = tf.constant([7, 10])
C.dtype

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [ ]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

In [ ]:
tensor.dtype

Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values.


In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D


In [ ]:
# Get the absolute values
tf.abs(D) 

Lets go through the following forms of aggregation:
.Get the minimum
.Get the maximum
.Get the mean of a tensor
.Get the sum of a tensor

In [ ]:
# Creating a random tensor with values btw and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

In [ ]:
tf.size