# Numpy -  multidimensional data arrays

## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` need to import the module it using of example:

In [ ]:
import numpy as np
np.set_printoptions(3, suppress=True)

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [ ]:
# a vector: the argument to the array function is a Python list
my_list = [1,2,3,4]
v = np.array(my_list)
v

array([1, 2, 3, 4])

In [ ]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4], [-1, 10]])
M

array([[ 1,  2],
       [ 3,  4],
       [-1, 10]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [ ]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [ ]:
v.shape

(4,)

In [ ]:
M.shape

(3, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [ ]:
M.size

6

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [ ]:
np.shape(M)

(3, 2)

In [ ]:
np.size(M)

6

So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementating such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [ ]:
M.dtype

dtype('int64')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [ ]:
M[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [ ]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
print(M)
print(M.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


Common type that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generates arrays of different forms. Some of the more common are:

#### arange

In [ ]:
# create a range
x = np.arange(0, 10, 1) # arguments: start, stop, step
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.arange(-1, 1, 0.1)
print(x)

[-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1 -0.   0.1  0.2  0.3
  0.4  0.5  0.6  0.7  0.8  0.9]


#### linspace and logspace

In [ ]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25)

array([ 0.   ,  0.417,  0.833,  1.25 ,  1.667,  2.083,  2.5  ,  2.917,
        3.333,  3.75 ,  4.167,  4.583,  5.   ,  5.417,  5.833,  6.25 ,
        6.667,  7.083,  7.5  ,  7.917,  8.333,  8.75 ,  9.167,  9.583,
       10.   ])

In [ ]:
np.logspace(0, 10, 10, base=np.e)

array([    1.   ,     3.038,     9.228,    28.032,    85.153,   258.671,
         785.772,  2386.965,  7250.958, 22026.466])

#### mgrid

In [ ]:
x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB

In [ ]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [ ]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### random data

In [ ]:
from numpy import random

In [ ]:
# uniform random numbers in [0,1]
# np.array(16 * random.rand(5, 7) + 1, dtype=int)
random.rand(5, 7)

array([[0.485, 0.818, 0.839, 0.991, 0.86 , 0.224, 0.042],
       [0.629, 0.574, 0.435, 0.458, 0.471, 0.593, 0.837],
       [0.838, 0.551, 0.196, 0.475, 0.126, 0.348, 0.741],
       [0.519, 0.326, 0.349, 0.364, 0.812, 0.043, 0.107],
       [0.602, 0.021, 0.723, 0.763, 0.04 , 0.844, 0.325]])

In [ ]:
# standard normal distributed random numbers
random.randn(5,5)

array([[ 1.255, -0.334, -0.053, -0.617, -0.559],
       [ 0.366,  0.118,  0.085,  0.128, -0.458],
       [ 0.061, -0.176, -2.883, -1.26 , -1.934],
       [ 1.348, -0.334, -1.271, -0.462,  1.946],
       [ 0.88 , -0.065,  0.384,  0.183,  0.299]])

#### diag

In [ ]:
# a diagonal matrix
np.diag([1, 2, 3, -4, 10])

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0, -4,  0],
       [ 0,  0,  0,  0, 10]])

In [ ]:
# diagonal with offset from the main diagonal
np.diag([1, 2, 3, -4, 10], k=1) 

array([[ 0,  1,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0, -4,  0],
       [ 0,  0,  0,  0,  0, 10],
       [ 0,  0,  0,  0,  0,  0]])

#### zeros and ones

In [ ]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## Manipulating arrays

### Indexing

We can index elements in an array using the square bracket and indices:

In [ ]:
# v is a vector, and has only one dimension, taking one index
v[2]

3

In [ ]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M = M.astype(np.int)
M[1, 1]

4

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [ ]:
M

array([[1, 2],
       [3, 4]])

In [ ]:
M[1]

array([3, 4])

The same thing can be achieved with using `:` instead of an index: 

In [ ]:
ran = np.random.rand(3, 4)
ran

array([[0.787, 0.116, 0.237, 0.46 ],
       [0.162, 0.026, 0.437, 0.041],
       [0.928, 0.438, 0.893, 0.638]])

In [ ]:
ran[:, 0]

array([0.787, 0.162, 0.928])

We can assign new values to elements in an array using indexing:

In [ ]:
ran

array([[0.787, 0.116, 0.237, 0.46 ],
       [0.162, 0.026, 0.437, 0.041],
       [0.928, 0.438, 0.893, 0.638]])

In [ ]:
ran[0, 0] = 1
print(ran)

[[1.    0.116 0.237 0.46 ]
 [0.162 0.026 0.437 0.041]
 [0.928 0.438 0.893 0.638]]


In [ ]:
# also works for rows and columns
ran

array([[1.   , 0.116, 0.237, 0.46 ],
       [0.162, 0.026, 0.437, 0.041],
       [0.928, 0.438, 0.893, 0.638]])

In [ ]:
ran[:, 1] = 50
ran

array([[ 1.   , 50.   ,  0.237,  0.46 ],
       [ 0.162, 50.   ,  0.437,  0.041],
       [ 0.928, 50.   ,  0.893,  0.638]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [ ]:
ran

array([[ 1.   , 50.   ,  0.237,  0.46 ],
       [ 0.162, 50.   ,  0.437,  0.041],
       [ 0.928, 50.   ,  0.893,  0.638]])

In [ ]:
ran[1:3, 2:4]

array([[0.437, 0.041],
       [0.893, 0.638]])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [ ]:
ran[0, 1:4] = [2, 4, 6]
ran

array([[ 1.   ,  2.   ,  4.   ,  6.   ],
       [ 0.162, 50.   ,  0.437,  0.041],
       [ 0.928, 50.   ,  0.893,  0.638]])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [ ]:
ran[::] # lower, upper, step all take the default values

array([[ 1.   ,  2.   ,  4.   ,  6.   ],
       [ 0.162, 50.   ,  0.437,  0.041],
       [ 0.928, 50.   ,  0.893,  0.638]])

In [ ]:
ran[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([[ 1.   ,  2.   ,  4.   ,  6.   ],
       [ 0.928, 50.   ,  0.893,  0.638]])

In [ ]:
ran[:3] # first three elements

array([[ 1.   ,  2.   ,  4.   ,  6.   ],
       [ 0.162, 50.   ,  0.437,  0.041],
       [ 0.928, 50.   ,  0.893,  0.638]])

In [ ]:
ran[3:] # elements from index 3

array([], shape=(0, 4), dtype=float64)

Negative indices counts from the end of the array (positive index from the begining):

In [ ]:
ran

array([[ 1.   ,  2.   ,  4.   ,  6.   ],
       [ 0.162, 50.   ,  0.437,  0.041],
       [ 0.928, 50.   ,  0.893,  0.638]])

In [ ]:
ran[-1] # the last row

array([ 0.928, 50.   ,  0.893,  0.638])

In [ ]:
ran[-1, -2:] # the last row last two cols

array([0.893, 0.638])

Index slicing works exactly the same way for multidimensional arrays:

In [ ]:
ran = np.array([[n+m*10 for n in range(5)] for m in range(5)])

ran

In [ ]:
# a block from the original array
ran[1:4, 1:4]

array([[50.   ,  0.437,  0.041],
       [50.   ,  0.893,  0.638]])

In [ ]:
# strides
ran[::2, ::2]

array([[1.   , 4.   ],
       [0.928, 0.893]])

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [ ]:
ran
row_indices = [0, 2]
ran[row_indices]

array([[ 1.   ,  2.   ,  4.   ,  6.   ],
       [ 0.928, 50.   ,  0.893,  0.638]])

In [ ]:
col_indices = [1, 2] # remember, index -1 means the last element
ran[row_indices, col_indices]

array([2.   , 0.893])

We can also index masks: If the index mask is an Numpy array of with data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position each element: 

In [ ]:
B = np.arange(5)
B

array([0, 1, 2, 3, 4])

In [ ]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [ ]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [ ]:
x = np.random.rand(20)
x

array([0.718, 0.015, 0.317, 0.608, 0.544, 0.136, 0.51 , 0.856, 0.974,
       0.241, 0.108, 0.519, 0.991, 0.654, 0.283, 0.62 , 0.214, 0.912,
       0.469, 0.099])

In [ ]:
print(x)
mask = (x > 0.5) * (x < 0.7)
print(mask)

[0.718 0.015 0.317 0.608 0.544 0.136 0.51  0.856 0.974 0.241 0.108 0.519
 0.991 0.654 0.283 0.62  0.214 0.912 0.469 0.099]
[False False False  True  True False  True False False False False  True
 False  True False  True False False False False]


In [ ]:
x[mask]

array([0.608, 0.544, 0.51 , 0.519, 0.654, 0.62 ])

## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [ ]:
indices = np.where(mask)
print(indices)

In [ ]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [ ]:
np.diag(A)

In [ ]:
np.diag(A, -1)

### take

The `take` function is similar to fancy indexing described above:

In [ ]:
v2 = np.arange(-3,3)
print(v2)

In [ ]:
row_indices = [1, 3, 5]
v2[row_indices] # fancy indexing

In [ ]:
v2.take(row_indices)

But `take` also works on lists and other objects:

In [ ]:
np.take([-3, -2, -1,  0,  1,  2], row_indices)

### choose

Constructs and array by picking elements form several arrays:

In [ ]:
which = [1, 0, 1, 0]
choices = [[-2,-2,-2,-2], [5,5,5,5]]

np.choose(which, choices)

## Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [ ]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [ ]:
v1 * 2

array([0, 2, 4, 6, 8])

In [ ]:
v1 + 2

array([2, 3, 4, 5, 6])

In [ ]:
A = np.random.rand(5, 5)
print(A)
print(A * 2)

[[0.642 0.943 0.164 0.408 0.36 ]
 [0.851 0.249 0.852 0.674 0.082]
 [0.59  0.57  0.321 0.691 0.065]
 [0.958 0.683 0.497 0.66  0.821]
 [0.854 0.671 0.068 0.717 0.538]]
[[1.283 1.885 0.329 0.815 0.719]
 [1.702 0.499 1.704 1.347 0.164]
 [1.179 1.14  0.642 1.381 0.13 ]
 [1.916 1.366 0.994 1.32  1.641]
 [1.707 1.341 0.136 1.433 1.076]]


### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [ ]:
x = np.arange(0, 10, 0.5)
print(x)
y = x ** 2
print(y)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 0.    0.25  1.    2.25  4.    6.25  9.   12.25 16.   20.25 25.   30.25
 36.   42.25 49.   56.25 64.   72.25 81.   90.25]


In [ ]:
z = np.sin(x)
z

array([ 0.   ,  0.479,  0.841,  0.997,  0.909,  0.598,  0.141, -0.351,
       -0.757, -0.978, -0.959, -0.706, -0.279,  0.215,  0.657,  0.938,
        0.989,  0.798,  0.412, -0.075])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [ ]:
A = np.matrix([[1, 2, 5], [3, -2, 0], [7, 2, -1]])
print(A)
B = np.matrix([[20], [-1], [8]])
print(B)

[[ 1  2  5]
 [ 3 -2  0]
 [ 7  2 -1]]
[[20]
 [-1]
 [ 8]]


In [ ]:
A ** 2

matrix([[42,  8,  0],
        [-3, 10, 15],
        [ 6,  8, 36]])

### Matrix algebra

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [ ]:
X = (A ** -1) * B
print(X)

[[1.]
 [2.]
 [3.]]


In [ ]:
Ainv = A ** -1
print(Ainv)

[[ 0.019  0.111  0.093]
 [ 0.028 -0.333  0.139]
 [ 0.185  0.111 -0.074]]


In [ ]:
A * Ainv

matrix([[ 1., -0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

Alternatively, we can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra.

In [ ]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector

In [ ]:
v

In [ ]:
M * M

In [ ]:
M * v

In [ ]:
# inner product
v.T * v

In [ ]:
# with matrix objects, standard matrix algebra applies
v + M*v

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [ ]:
v = np.matrix([1,2,3,4,5,6]).T

In [ ]:
np.shape(M), np.shape(v)

In [ ]:
M * v

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

### Array/Matrix transformations

Above we have used the `.T` to transpose the matrix object `v`. We could also have used the `transpose` function to accomplish the same thing. 

Other mathematical functions that transforms matrix objects are:

In [ ]:
C = np.matrix([[1j, 2j], [3j, 4j]])
C

In [ ]:
np.conjugate(C)

Hermitian conjugate: transpose + conjugate

In [ ]:
C.H

We can extract the real and imaginary parts of complex-valued arrays using `real` and `imag`:

In [ ]:
np.real(C) # same as: C.real

In [ ]:
np.imag(C) # same as: C.imag

Or the complex argument and absolute value

In [ ]:
np.angle(C+1) # heads up MATLAB Users, angle is used instead of arg

In [ ]:
abs(C)

### Matrix computations

#### Inverse

In [ ]:
np.linalg.inv(C) # equivalent to C.I 

In [ ]:
C.I * C

#### Determinant

In [ ]:
np.linalg.det(C)

In [ ]:
np.linalg.det(C.I)

### Data processing

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays. 

In [ ]:
data = np.random.rand(100)
print(data)

[0.396 0.026 0.342 0.717 0.231 0.404 0.359 0.336 0.29  0.396 0.598 0.012
 0.638 0.697 0.843 0.588 0.214 0.313 0.857 0.086 0.907 0.844 0.163 0.19
 0.388 0.702 0.444 0.699 0.694 0.63  0.945 0.719 0.685 0.293 0.299 0.78
 0.888 0.347 0.569 0.535 0.695 0.609 0.522 0.496 0.179 0.774 0.843 0.898
 0.688 0.727 0.547 0.908 0.456 0.67  0.156 0.116 0.073 0.176 0.731 0.998
 0.84  0.479 0.176 0.114 0.524 0.251 0.034 0.35  0.317 0.735 0.028 0.395
 0.701 0.61  0.377 0.78  0.262 0.762 0.897 0.071 0.778 0.911 0.604 0.291
 0.757 0.422 0.596 0.931 0.499 0.433 0.354 0.689 0.304 0.359 0.315 0.829
 0.212 0.609 0.45  0.833]


In [ ]:
np.shape(data)

(100,)

#### mean

In [ ]:
np.mean(data)

0.5120909725670912

#### standard deviations and variance

In [ ]:
np.std(data), np.var(data)

(0.26231132938655843, 0.06880723352454356)

#### min and max

In [ ]:
data.min()

0.012297514368973639

In [ ]:
data.max()

0.998374639143025

#### sum, prod, and trace

In [ ]:
d = np.arange(0, 10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# sum up all elements
sum(d)

45

In [ ]:
# product of all elements
np.prod(d+1)

3628800

In [ ]:
# cummulative sum
np.cumsum(d)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
# cummulative product
np.cumprod(d+1)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [ ]:
# same as: diag(A).sum()
print(np.trace(A))
print(np.linalg.matrix_rank(A))
print(np.linalg.eig(A))

-2
3
(array([ 6.69, -6.  , -2.69]), matrix([[-0.687, -0.601,  0.219],
        [-0.237,  0.45 , -0.951],
        [-0.687,  0.661,  0.219]]))


### Polynomials

Construct the polynomial $x^2 + 2x + 3$:

In [ ]:
p = np.poly1d([1, 2, 3])
print(np.poly1d(p))

   2
1 x + 2 x + 3


Evaluate the polynomial at $x = 0.5$:

In [ ]:
p(0.5)

4.25

In [ ]:
# Find the roots:
p.r

array([-1.+1.414j, -1.-1.414j])

In [ ]:
# Show the coefficients:
p.c

array([1, 2, 3])

In [ ]:
# Display the order (the leading zero-coefficients are removed):
p.order

2

In [ ]:
# Show the coefficient of the k-th power in the polynomial (which is equivalent to p.c[-(i+1)]):
p[1]

2

In [ ]:
# Polynomials can be added, subtracted, multiplied, and divided (returns quotient and remainder):
p * p

poly1d([ 1,  4, 10, 12,  9])

In [ ]:
(p**3 + 4) / p

(poly1d([ 1.,  4., 10., 12.,  9.]), poly1d([4.]))

In [ ]:
p**2 # square of polynomial

poly1d([ 1,  4, 10, 12,  9])

In [ ]:
np.square(p) # square of individual coefficients

array([1, 4, 9])

In [ ]:
# The variable used in the string representation of p can be modified, using the variable parameter:
num = np.poly1d([1, 2, 3], variable='s')
print(num)
den = np.poly1d([5, 3, 6, 10], variable='s')
print(den)
G = num / den
print(G)
print(f'The poles are at {den.r}')

   2
1 s + 2 s + 3
   3     2
5 s + 3 s + 6 s + 10
(poly1d([0.]), poly1d([1., 2., 3.]))
The poles are at [ 0.261+1.31j  0.261-1.31j -1.121+0.j  ]


In [ ]:
# Construct a polynomial from its roots:
np.poly1d([1, 2], True)

poly1d([ 1., -3.,  2.])

In [ ]:
# This is the same polynomial as obtained by:
np.poly1d([1, -1]) * np.poly1d([1, -2])

poly1d([ 1, -3,  2])